### ISSUE TITLE
Cuadro de confirmacion

### ISSUE THREAD

**Issue by neossoftware** [hhugohm/angular1#11]
@hhugohm  se agrego el cuadro de confirmacion deacuerdo al manual siguiente
https://code.ciphertrick.com/2016/05/23/fancy-alert-confirm-box-angularjs/

El branch es: fix/confirm
Favor de validar la funcionalidad y en caso de ser satisfactorio hacer el pull request

**Comment by hhugohm** [comment]
Es correcta la implementacion del usuario con la funcionalidad del alert se realizar el merge con el pull request https://github.com/hhugohm/angular1/pull/13
