### ISSUE TITLE
Crear las tareas Gulp para el proyecto

### ISSUE THREAD

**Issue by neossoftware** [hhugohm/angular1#20]
@hhugohm ya estoy haciendo la configuracion Gulp con la informacion del libro de gulp que esta en mi cuenta de amazon, dicha configuracion puede verse el avance en el branch

**Comment by hhugohm** [comment]
Ok, lo reviso y espero entender un poco jaja porque de eso no se nada

Saludos

**Comment by neossoftware** [comment]
@hhugohm calma ya tengo un avance de gulp mañana hago el pullrequest para que lo cheques cuando puedas ;) el branch es gulptasks

**Comment by hhugohm** [comment]
Bambi

Me late apa, bonito pull request

**Comment by neossoftware** [comment]
@hhugohm  se ha concluido la configuracion de devrelease de gulp, faltaria la configuracion de PRD, generar la minificacion de JS y CSS
