### ISSUE TITLE
Agregar un layaout al front end

### ISSUE THREAD

**Issue by neossoftware** [hhugohm/angular1#4]
Agregar un layout al sistema front end, es decir que tenga un menu, con las opciones de desplegar todos los usuarios, etc , es por ese motivo que se genera el branch fixfrontend :P

**Comment by hhugohm** [comment]
@neossoftware Alguna idea para poder comenzar a trabajar en el menu?? Algun ejemplo? algo de guia
Gracias

**Comment by neossoftware** [comment]
Si bro, hay unos admin template en internet: http://rdash.github.io/#/

Aqui puedes decargar el codigo, esta bueno echale un ojito
https://github.com/rdash/rdash-angular
